port = 7777
tls_port = 443

tls_enabled=true
tls_private_cert="./config/private.pem"
tls_chain_cert="./config/chain.pem"


#vault_address = "https://localhost"
#role_id = "adsadas"
#secret_id = "asdasdsad"
#path_to_cert_secret = "path/test_certz"
#aws_access_key = "zbz"
#aws_secret_key = "zbz"
#consul_url = "localhost"
#fqdns = ["experimental.max"]
#r53_zone_id = "XXXX"

consul_pool_secs = 60
consul_leader_pool_secs = 600
log_path="/opt/pproxy2/logs"

#hostname(contains) -> consul service name
[host_to_upstream]
snpfa = "pipeline-snpfa-service"
alert-service = "pipeline-alert-service"
config-ui = "pipeline-config-ui"
device-portal-rest-api = "pipeline-device-portal-rest-api"
config-service = "pipeline-config-service"
kibana = "pipeline-kibana"
grafana = "pipeline-grafana"